global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Qwen Image API 监控
  - job_name: 'qwen-image-api'
    static_configs:
      - targets: ['qwen-image-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis 监控（需要 redis_exporter）
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx 监控（需要 nginx-prometheus-exporter）
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # 节点监控（需要 node_exporter）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']